version: '3.7'
services:
  collector:
    image: otel/opentelemetry-collector:0.43.0
    volumes:
    - ./otel-local-config.yaml:/otel-local-config.yaml
    entrypoint: ["/otelcol"]
    command: ["--config", "/otel-local-config.yaml"]
    environment:
      LOG_EXPORTER_LOG_LEVEL: "DEBUG"
    ports:
    - "4317:4317"
    - "16685:16685"