receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  
exporters:
  logging:
    logLevel: debug
  #zipkin:
    #endpoint: "http://zipkin:9411"
    #insecure: true
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]