version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
  loadbalancer:
    image: otel/opentelemetry-collector-contrib
    container_name: loadbalancer
    volumes:
    - ./otel-balancer-config.yaml:/otel-local-config.yaml
    command: ["--config", "/otel-local-config.yaml"]
    ports:
    - "4317:4317"
    - "8888:8888"
    - "8889:8889"
  collector:
    image: otel/opentelemetry-collector-contrib
    container_name: collector
    volumes:
    - ./otel-local-config.yaml:/otel-local-config.yaml
    - ./:/etc/output:rw
    command: ["--config", "/otel-local-config.yaml"]
    ports:
    - "16685:16685"
    - "55690:55690"
networks:
  default:
    external: true
    name: my-net