receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  tail_sampling:
    decision_wait: 5s
    num_traces: 100 #default 50000
    expected_new_traces_per_sec: 1
    policies:
      [
          {
            name: probabilistic-policy,
            type: probabilistic,
            probabilistic: {sampling_percentage: 25}
          },
          {
            name: latency-policy,
            type: latency,
            latency: {threshold_ms: 200}
          },
          {
            name: errors-policy,
            type: string_attribute,
            string_attribute: {key: error, values: true}
          }
      ]

exporters:
  logging:
    logLevel: debug
  prometheus:
    endpoint: 0.0.0.0:8889
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  file:
    path: /etc/output/logs.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]