global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    scrape_interval: 10s
    static_configs:
      - targets: ['loadbalancer:8889']
      - targets: ['loadbalancer:8888']
      