global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    scrape_interval: 10s
    static_configs:
      - targets: ['collector:8889']
      - targets: ['collector:8888']
      